/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.dreampany.tools.api.wordnik.model

import kotlin.Long

/**
 *
 * @param documentId
 * @param exampleId
 * @param id
 * @param provider
 * @param rating
 * @param score
 * @param sentence
 * @param text
 * @param title
 * @param url
 * @param word
 * @param year
 */
data class Example(
    val documentId: Long = 0L,
    val exampleId: Long = 0L,
    val id: Long = 0L,
    val provider: ContentProvider? = null,
    val rating: Float? = null,
    val score: ScoredWord? = null,
    val sentence: Sentence? = null,
    val text: String? = null,
    val title: String? = null,
    val url: String? = null,
    val word: String? = null,
    val author: String? = null,
    val year: Int? = null
)

